openapi: 3.0.3
info:
  title: OpenAPI definition
  version: v1
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  "/user-storage/profiles":
    get:
      tags:
        - user-controller
      operationId: getProfiles
      description: returns all the available user profiles
      responses:
        '200':
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/User"
    post:
      tags:
        - user-controller
      operationId: createUserProfile
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/User"
      responses:
        '200':
          description: OK
          content:
            "application/json":
              schema:
                "$ref": "#/components/schemas/User"

  "/user-storage/profile/{userId}":
    get:
      tags:
        - user-controller
      operationId: getUserProfile
      description: returns user's profile
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            "application/json":
              schema:
                "$ref": "#/components/schemas/User"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        fullName:
          type: string
        placeOfBirth:
          type: string
        dateOfBirth:
          type: string
          format: date
        createdAt:
          type: string
          format: date-time
        shippings:
          type: array
          items:
            $ref: '#/components/schemas/Shipping'
        phones:
          type: array
          items:
            $ref: '#/components/schemas/Phone'
    Shipping:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'
    Address:
      type: object
      properties:
        country:
          type: string
        street:
          type: string
    Phone:
      type: object
      properties:
        phoneNumber:
          type: string

